### PR TITLE
Support for dynamic OnVIF endpoint.  JSON encoding of OnVIF error messages.

### PR DESCRIPTION
**Pull request by jgarciasacristan**
The following routes have been added:
`/v1/devices/:id/onvif/v20/GetDeviceInformation`
`/v1/devices/:id/onvif/v20/GetNetworkInterfaces `
`/v1/devices/:id/onvif/v20/GetCapabilities`
`/v1/devices/:id/onvif/v20/GetProfiles`
`/v1/devices/:id/onvif/v20/GetServiceCapabilities` 
`/v1/devices/:id/onvif/v20/GetSnapshotUri/:profile`

Still pending:
- Addition to dashboard
- Extract url/username/password from URL as OnVIF will be used to query information when adding a camera. Should be trivial by using the Plug.

These routes need to be added to the dashboard. For now are only available in evercam-media.

"/v1/cameras:/id/macaddr" has been removed. MAC address can be obtained from ` /v1/devices/:id/onvif/v20/GetDeviceInformation`

You may be surprised to see /devices/ instead of /cameras. Discussion about this issue can be found in https://github.com/evercam/evercam-media/issues/131. 

Big refactoring going on in OnVIF. It now uses the connection to figure out which operation needs to invoke and a Plug to extract url/username/password from DB. This will help a lot when adding new commands. PTZ still needs more refactoring. I have touched it a little bit but I am afraid to break it a this point. I'll deal with PTZ later.Too tired at the moment. :-) 

~

### CODE REVIEW

**Comment by marcoherbst** [comment]
Wow @jgarciasacristan that was fast. 

TBH, I'm still a little nervous about /devices ... It's amazing that you went ahead and got that live, I'll need to talk through that concept with @mosic @azharmalik3 and @shankardevy ... I think it's correct (to enable us to nicely work with NVRs, Encoders, DVRs) but I'm not confident.

M

**Comment by jgarciasacristan** [comment]
I had a busy weekend. :)
Whatever you decide, it will only takes a couple of minutes to update the routes' path.

**Comment by marcoherbst** [comment]
@mosic if this is waiting for you, don't let my comments hold you back.
m

**Comment by jgarciasacristan** [comment]
It can be simplified even more. A route like`/v1/devices/:id/onvif/v20/:ns/:operation` will allow to invoke all operations with no parameters at once. :ns being "device", "media", "recording", "ptz" ...  This enhancement should be trivial to implement on top of this PR. Adding parameters to this dynamic route will complicate things a little bit but still doable. One thing at a time. :)

**Comment by mosic** [comment]
Hi @jgarciasacristan, that looks good. Is this free to merge or are you planning on adding something more? If I understood correctly the API endpoints need to be updated first?

**Comment by jgarciasacristan** [comment]
It is really free to merge. I can add the API endpoints to evercam-api
later on. I think will be good to have this refactoring in master and
provide the rest in another PR.

**Comment by mosic** [comment]
Just to be clear, if I merge and deploy now the MAC addresses endpoint will start working, right?

**Comment by jgarciasacristan** [comment]
Yes. As it is now, macaddr will stop working has it has been replaced by
/v1/devices/:id/onvif/v20/GetNetworkInterfaces. Is it difficult to delete
macaddr endpoint until I update evercam-api (probably by tomorrow night).?

**Comment by mosic** [comment]
Ok. I don't think that anything relies on that endpoint, so I'll just deploy this later today and that endpoint will be fixed when you make a PR for evercam-api.

Thanks for the PR :+1:

**Comment by jgarciasacristan** [comment]
@mosic  Hi, I have added a cool option that will make future onvif invocations very easy. You can now invoke OnVIF commands that do not require parameters dinamically from the URL. It is something like `/v1/devices/:id/onvif/v20/:service/:method`. See tests for more details on how to use it. Sorry for the update of the PR but I wanted to add this stuff before I forget. Next step: modify evercam-api.

**Comment by jgarciasacristan** [comment]
Support of the features described below:
There is a generic endpoint in -media that will have the following format:
/v1/onvif/v20/:service/:operation?url=url&auth=username:password&parameter_1=value_1&....&parameter_n=value_n

 A query argument defined as ?url=type://host;port&auth=username:password is used to provide access information.

:service - the following values are supported:
device_service
Analytics
Events
DeviceIO
AnalyticsDevice
Display
Imaging
Media
PTZ
Receiver
RemoteDiscovery
Recording
Replay
Search

:operation - any of the operations described in http://www.onvif.org/onvif/ver20/util/operationIndex.html

parameter_n=value_n - Input parameters described in each of the operations

Usage
The endpoint to invoke the Media operation GetSnapshotUri in mobile_mast camera looks like /v1/devices/onvif/v20/Media/GetSnapshotUri?ProfileToken=Profile1&id=mobile_mast 

There is no need to define this endpoint in evercam-media. It will be defined directly in evercam-api if needed. It will then use the dynamic evercam-media OnVIF endpoint.

When a camera is created the camera won’t be on the database so in order to read the Network Capabilities, for example, the following endpoint can be invoked:
/v1/onvif/20/device_service/GetNetworkCapabilities?url=http://149.13.244.32:8100&auth=admin:mehcam

Same applies for GetSnapshotUri or any other OnVIF operation
/v1/onvif/v20/Media/GetSnapshotUri?url=http://149.13.244.32:8100&auth=admin:mehcam&ProfileToken=Profile_1

Once this dynamic -media endpoint is built, it is just a matter of populating the most popular OnVIF commands in evercam-api. We will need be also an endpoint in -api that will allow to invoke any OnVIF command by populating the required fields. RISK: It could be tricky with complex nested input parameters.

Note: PTZ controller has not been modified. The existing PTZ endpoints are still valid.
Error handling has been improved.

**Comment by mosic** [comment]
Hi @jgarciasacristan, that looks good! Do you think it's ready to merge/deploy?

Before the actual merge, can I ask you to update the code which uses pipes according to the Elixir style guide (https://github.com/niftyn8/elixir_style_guide#source-code-layout)? That's the only thing that sticks out for me.

**Comment by jgarciasacristan** [comment]
Thanks! Yes, I think it is ready.
Thanks for the Elixir style guide again :-). I can now see how messy my pipes are. I'll fix it this evening.

**Comment by jgarciasacristan** [comment]
Pipes related code formatted. I think this is ready to go.

**Comment by mosic** [comment]
@jgarciasacristan Thanks, that looks good. I'll try to merge and deploy it tomorrow.

**Comment by jgarciasacristan** [comment]
@mosic More error handling logic added to deal with some issues I came across yesterday. Last commit of this PR unless you find something that need to be fixed before merge. Do not hesitate to ask :-)

**Comment by mosic** [comment]
@jgarciasacristan Thanks, merged and deployed just now. There was a small issue that you can see fixed on master, but otherwise it looks good. :+1:

**Pull request merged**
