### PR TITLE
Motion detection

### PR DESCRIPTION
**Pull request by mosic**
Original: https://github.com/evercam/evercam-media/pull/32

### CODE REVIEW

**Comment by eugenehp** [comment]
@mosic just commented on some of the changes. please take a look and let me know.

@marcoherbst I'll add the remaining parts to this pull request, once @mosic grants me write access to this branch `motion_detection`

**Comment by mosic** [comment]
@eugenehp I uncommented out that `:ok` because I was getting a NIF load error, and thought it fixed it, but I was wrong. I reverted the changes today.

We're using Erlang releases in production and it seems that there's a problem with creating a release with your motion detection code. Can you look into it?

You can replicate the error by running the following in `evercam-media` directory:

```
rm -rf rel; mix release; rel/evercam_media/bin/evercam_media foreground
```

You should get something similar to this:

```
{error_logger,{{2015,8,19},{12,33,52}},crash_report,[[{initial_call,{supervisor,kernel,['Argument__1']}},{pid,<0.1138.0>},{registered_name,[]},{error_info,{exit,{on_load_function_failed,'Elixir.EvercamMedia.Motiondetection'},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,330}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[kernel_sup,<0.1116.0>]},{messages,[]},{links,[<0.1117.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,124}],[]]}
{error_logger,{{2015,8,19},{12,33,52}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{on_load_function_failed,'Elixir.EvercamMedia.Motiondetection'}},{offender,[{pid,undefined},{name,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2015,8,19},{12,33,53}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.1115.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.EvercamMedia.Motiondetection'}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.1114.0>]},{messages,[{'EXIT',<0.1116.0>,normal}]},{links,[<0.1114.0>,<0.1113.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2015,8,19},{12,33,53}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.EvercamMedia.Motiondetection'}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.EvercamMedia.Motiondetection'}}},{kernel,start,[normal,[]]}}}"}

```

**Comment by eugenehp** [comment]
Thanks Miloš,

I'll take a look and let you know. Would you mind to tell me which exact
flow do you use for the releases in Erlang?

Regards,
Eugene

**Comment by mosic** [comment]
Sure, we currently use this Ansible task for generating a release and deploying: [bootstrap.yml](https://github.com/evercam/evercam-devops/blob/696e75192ff937252eaa18ec405272cecdd6d384/ansible/elixir_setup/media/tasks/bootstrap.yml).

The command `mix release` I gave in the previous comment comes from https://github.com/bitwalker/exrm, which does all the heavy lifting.

**Comment by eugenehp** [comment]
gotcha. looking into it already.

**Comment by eugenehp** [comment]
hey Miloš,

So the trick is to `make` first, so you can have the binary compiled, and
then it passes just fine. I'll correct the ansible instructions.

Let me know if it works for you.

Regards,
Eugene

**Comment by eugenehp** [comment]
```
mac:evercam-media iii$ make
rm -f -r priv_dir/*
cc -g -O3 -ansi -pedantic -Wall -Wextra -Wno-declaration-after-statement -Wno-missing-field-initializers -Wno-pedantic -Wno-implicit-function-declaration -I/usr/local/Cellar/erlang/17.5/lib/erlang/erts-6.4/include -fPIC -shared -dynamiclib -undefined dynamic_lookup -ljpeg -o priv_dir/lib_elixir_motiondetection.so c_src/lib_elixir_motiondetection.c -ljpeg
mac:evercam-media iii$ ls priv
priv/     priv_dir/ 
mac:evercam-media iii$ ls priv_dir/
lib_elixir_motiondetection.so		lib_elixir_motiondetection.so.dSYM
mac:evercam-media iii$ mix release
mix.exs:15: warning: function aliases/0 is unused
rm -f -r priv_dir/*
cc -g -O3 -ansi -pedantic -Wall -Wextra -Wno-declaration-after-statement -Wno-missing-field-initializers -Wno-pedantic -Wno-implicit-function-declaration -I/usr/local/Cellar/erlang/17.5/lib/erlang/erts-6.4/include -fPIC -shared -dynamiclib -undefined dynamic_lookup -ljpeg -o priv_dir/lib_elixir_motiondetection.so c_src/lib_elixir_motiondetection.c -ljpeg

Compiled lib/media/elixir_worker.ex
Compiled lib/media.ex
Compiled lib/media/worker_supervisor.ex
web/channels/snapshot_channel.ex:4: warning: variable camera_id is unused
lib/evercam_media/http_client.ex:44: warning: variable hd is unused
lib/evercam_media/http_client.ex:44: warning: variable tl is unused
lib/evercam_media/http_client.ex:48: warning: variable cookie is unused
Compiled web/channels/snapshot_channel.ex
Compiled lib/motiondetection.ex
Compiled lib/media/json.ex
Compiled lib/evercam_media/http_client.ex
Compiled lib/media/repo.ex
Compiled web/models/camera_activity.ex
Compiled web/models/app.ex
Compiled web/models/cloud_recording.ex
Compiled web/models/camera_share.ex
Compiled web/models/country.ex
lib/snapshots/snapshot_fetch.ex:163: warning: clause with defaults should be the first clause in def save_snapshot_record/9
Compiled web/models/snapshot.ex
Compiled web/web.ex
Compiled web/models/user.ex
lib/snapshots/snapshot_fetch.ex:157: warning: variable file_timestamp is unused
Compiled web/models/vendor.ex
Compiled web/models/vendor_model.ex
Compiled lib/media/worker.ex
Compiled lib/snapshots/snapshot_fetch.ex
web/models/camera.ex:56: warning: variable port is unused
web/models/camera.ex:56: warning: variable type is unused
web/models/camera.ex:82: warning: variable recording_cameras is unused
Compiled web/models/camera.ex
lib/media/s3.ex:60: warning: variable expires is unused
Compiled lib/media/s3.ex
web/controllers/snapshot_controller.ex:159: warning: function check_token_expiry/1 is unused
web/controllers/stream_controller.ex:26: warning: variable params is unused
Compiled web/controllers/stream_controller.ex
web/controllers/snapshot_controller.ex:58: warning: variable params is unused
web/controllers/snapshot_controller.ex:67: warning: variable params is unused
web/controllers/snapshot_controller.ex:81: warning: variable params is unused
web/controllers/snapshot_controller.ex:151: warning: variable timestamp is unused
Compiled web/controllers/snapshot_controller.ex
Compiled web/controllers/page_controller.ex
Compiled web/router.ex
Compiled web/views/error_view.ex
Compiled web/views/page_view.ex
Compiled web/views/layout_view.ex
Compiled lib/media/endpoint.ex
Generated evercam_media app
==> Building release with MIX_ENV=dev.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
==> Generating nodetool...
==> Packaging release...
==> The release for evercam_media-1.0.0 is ready!
```

**Comment by mosic** [comment]
@eugenehp `mix release` runs `make` automatically because it was added to compilers, so that doesn't change anything.

Generating the release worked before too, the error occurs when you try to run the application (with `rel/evercam_media/bin/evercam_media foreground`).

**Comment by eugenehp** [comment]
@mosic thanks for pointing this out, let me check this and I'll ping you back here.

**Comment by mosic** [comment]
@eugenehp Thanks, I'll most likely be back online tonight.

**Comment by eugenehp** [comment]
Hey @mosic 
Just compiled this inside Vagrant
Looks fine to me
screenshot

**Comment by mosic** [comment]
@eugenehp Are you on the master branch? That's how it looks for me on master.

If I do `git pull; git checkout origin/motion_detection; rm -rf rel; mix release; rel/evercam_media/bin/evercam_media foreground` I get the errors I mentioned above.

**Comment by eugenehp** [comment]
@mosic interesting

if you do this `cp -r priv_dir/ rel/evercam_media/priv_dir` from the `evercam-media` folder, then I get

```
mac:evercam-media iii$ rel/evercam_media/bin/evercam_media foreground
Exec: /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media/erts-6.4/bin/erlexec -noshell -noinput +Bd -boot /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media/releases/1.0.0/evercam_media -mode embedded -config /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media/releases/1.0.0/sys.config -boot_var ERTS_LIB_DIR /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media/erts-6.4/../lib -args_file /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media/releases/1.0.0/vm.args -- foreground
Root: /Users/iii/Documents/GitHub/evercam-devops/evercam-media/rel/evercam_media
[Porcelain]: goon executable not found
[Porcelain]: falling back to the basic driver

[info] Application exq exited: Exq.start(:normal, []) returned an error: shutdown: failed to start child: Exq.Manager
    ** (EXIT) {:connection_error, {:connection_error, :econnrefused}}
{"Kernel pid terminated",application_controller,"{application_start_failure,exq,{{shutdown,{failed_to_start_child,'Elixir.Exq.Manager',{connection_error,{connection_error,econnrefused}}}},{'Elixir.Exq',start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,exq,{{shutdown,{failed_to_start_child,'Elixir.Exq.Manager',{connection_error,{connection_error,econnrefused}}}},{'Elixir.Ex
```

**Comment by eugenehp** [comment]
Hey @mosic 
Just compiled this inside Vagrant, second time with a `origin/motion_detection` branch,
Looks fine to me
screenshot

Can you please take a look and let me know if it works for you this way? Don't forget to `cp -r priv_dir/ rel/evercam_media/priv_dir`

**Comment by eugenehp** [comment]
@mosic @marcoherbst https://github.com/evercam/evercam-devops/blob/motion-detection-second/README.md#another-way-to-execute-media-server

**Comment by mosic** [comment]
@eugenehp Yup, I get the same result now. Btw is there a reason not to add `*.so` to `.gitignore`?

**Comment by eugenehp** [comment]
@mosic awesome. sure we can add it to .gitignore, since we are using debian based OS in all stages, then it's easier to carry the `*.so` file around for faster tests, however I think it makes sense to put it into `*.gitignore` when the motion detection is tested and finished.

Makes sense?

**Comment by mosic** [comment]
@eugenehp Yes. I tried the branch in production but got `double free or corruption` errors. We can continue on Slack.

**Comment by eugenehp** [comment]
@mosic can I ask you please to provide me with the command you used to run the elixir application on the AWS instance you created yesterday? thanks!

**Comment by mosic** [comment]
@eugenehp I used `sudo start evercam_media`.

**Comment by eugenehp** [comment]
@mosic thanks. have you had a chance to discover what was the reason of that crash yesterday?

**Comment by mosic** [comment]
@eugenehp No, I worked on something else today. I may have some time tomorrow though.

**Comment by marcoherbst** [comment]
Isn't it likely to be CPU ?

current media = 70%
motion detection (on larger instance) = 30%

70%+30%= ?

Perhaps this is an oversimpilfication.

M



On 20 August 2015 at 19:11, Miloš Mošić <notifications@github.com> wrote:

> @eugenehp <https://github.com/eugenehp> No, I worked on something else
> today. I may have some time tomorrow though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/pull/33#issuecomment-133104331>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@marcoherbst Yes, that is an oversimplification.

Instance 1: evercam-media master
Instance 2: evercam-media master + motion detection

Instance 2 is about twice as large, so you can't make accurate comparisons.

**Comment by mosic** [comment]
Superseded by https://github.com/evercam/evercam-media/pull/93.

**Pull request closed without merging**
