### PR TITLE
Use :api pipeline, get default_profile from configuration, add 3 new onvif routes, use evercam_tst database in tests, basic loggin on onvif_client

### PR DESCRIPTION
**Pull request by jgarciasacristan**
- Use :api pipeline for onvif routes
- Add /v1/cameras/:id/camerainfo route
- Add /v1/cameras/:id/networkinterfaces route
- Add /v1/cameras/:id/profiles route
- Use pattern matching to extract camera id in controllers
- Move get_camera_info function to web/models/camera.ex so it can be used by the controllers
- Define default_profile property in config.exs under the onvif scope. Ultimately this string needs to be part of the Camera DB as it may change among camera vendors.
- Use evercam_tst database in unit tests and populate with sample camera as part of unit tests execution.
- Add basic logging in onvif_client so SOAP traffic is logged in case of failure.

### CODE REVIEW

**Comment by jgarciasacristan** [comment]
@mosic  Can you now successfully run the unit tests?

**Comment by mosic** [comment]
@jgarciasacristan Yes, after manually purging the test database it worked nicely.

On the other hand there is a problem with the PTZ feature in production, I'm looking into it right now.

**Comment by jgarciasacristan** [comment]
@mosic  I have noticed that. I am interested in this output from the logs:
https://github.com/evercam/evercam-media/blob/master/lib/onvif/onvif_client.ex#L23 
It should show the SOAP conversation.

**Comment by mosic** [comment]
@jgarciasacristan This is the error output:

```
Request: POST /v1/cameras/mobile-mast/ptz/home?(api keys removed)
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:xop=\"http://www.w3.org/2004/08/xop/include\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><env:Fault><env:Code><env:Value>env:Sender</env:Value>\r\n<env:Subcode><env:Value>ter:InvalidArgVal</env:Value>\r\n<env:Subcode><env:Value>ter:InvalidParameter</env:Value>\r\n</env:Subcode>\r\n</env:Subcode>\r\n</env:Code>\r\n<env:Reason><env:Text xml:lang=\"en\">the parameter value is illegal</env:Text>\r\n</env:Reason>\r\n</env:Fault>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "2289", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Mon, 28 Sep 2015 21:54:18 GMT", Server: "App-webs/"], status_code: 500}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        (evercam_media) lib/onvif/onvif_client.ex:23: EvercamMedia.ONVIFClient.onvif_call/7
        (evercam_media) web/controllers/onvifptz_controller.ex:43: EvercamMedia.ONVIFPTZController.home/2
        (evercam_media) web/controllers/onvifptz_controller.ex:1: EvercamMedia.ONVIFPTZController.phoenix_controller_pipeline/2
        (evercam_media) lib/phoenix/router.ex:297: EvercamMedia.Router.dispatch/2
        (evercam_media) lib/phoenix/router.ex:2: EvercamMedia.Router.call/2
        (evercam_media) lib/media/endpoint.ex:1: EvercamMedia.Endpoint.phoenix_endpoint_pipeline/1
```

The weird thing is that the same code works perfectly fine in development.

**Comment by jgarciasacristan** [comment]
Damn. The log string is broken. Going to fix it. That way I will be able to
see the request as well.

**Comment by jgarciasacristan** [comment]
https://github.com/evercam/evercam-media/pull/68 created. This fix will enable me to see the SOAP request as well.

**Comment by mosic** [comment]
@jgarciasacristan I figured it out. The request was failing because onvif profile wasn't set. Because it was  configured to use `Application.get_env` to get the default value, it wasn't available in the compiled release and therefore worked in development, but not in production.

You haven't done anything wrong though. I can see the `onvif` configuration in the `exrm` generated `sys.config` file, so it should work. I'll look into it, created an issue here: https://github.com/evercam/evercam-media/issues/69

Thanks for the pull request!

**Comment by jgarciasacristan** [comment]
One workaround would be to replace all  Application.get_env(:onvif,
:default_profile) calls in the controllers code with Application.get_env(
:onvif, :default_profile, "Profile_1") or wrap this call in a getProfile
method that can be included in lib/onvif_client.ex. I can create a pull
request this evening

**Comment by jgarciasacristan** [comment]
Actually, having a generic default configuration does not add any value really. The idea was to have a place to change it quickly if we needed to do it for my demo two weeks ago. At this moment, having hardcoded to "Profile_1" in the controller's code is ok. In my opinion, the proper fix is to have the profile defined as a property in the camera database.

**Comment by mosic** [comment]
@jgarciasacristan Missed the first message. I completely agree, what we have is fine for now, storing the profile in the database should be the next step. Can the profile be changed using the onvif commands?

**Comment by jgarciasacristan** [comment]
Yes, you can create and delete profiles. All profile based operations are described in http://www.onvif.org/onvif/ver10/media/wsdl/media.wsdl.

**Pull request merged**
