### PR TITLE
Ie authorization

### PR DESCRIPTION
**Pull request by fteem**

### CODE REVIEW

**Comment by fteem** [comment]
@mosic @shankardevy can you guys take a look at this and let me know what you think?

**Comment by eugenehp** [comment]
hey @fteem nice work, is this something bigger than resource ACL, how do you see Authorizer when it's fully finished?

**Comment by fteem** [comment]
Thanks Eugene.

What do you mean by ACL?

**Comment by eugenehp** [comment]
@fteem something like [Access Control List](https://en.wikipedia.org/wiki/Access_control_list)

**Comment by mosic** [comment]
@fteem Looks good to me so far :+1: 

@eugenehp This is a re-implementation of authorization layer we use in `evercam-api` (https://github.com/evercam/evercam-models/tree/master/lib/evercam_models), we won't do anything crazy until `evercam-media` achieves feature parity with `evercam-api`.

**Comment by eugenehp** [comment]
@mosic gotcha, thanks for the clarification Milos.

**Comment by fteem** [comment]
@mosic thanks. Do you think the logic is sound here?

@eugenehp well, yeah. It's very far from done, but I think that I am aiming at something like that. Basically, I'd like to pass a resource and a user to the authorizer and get a boolean back for a certain action.

**Comment by mosic** [comment]
@fteem Yes, and it seems easier to follow than the old implementation.

**Comment by eugenehp** [comment]
@marcoherbst remind me about this on Friday please, have some thoughts to elaborate. Thanks.

**Comment by fteem** [comment]
@mosic can we talk about getting this into master today/tomorrow? Also, see the latest commit.

**Comment by mosic** [comment]
@fteem sure, that sounds good. Also the last commit looks good.

**Comment by fteem** [comment]
Remarks from call with Milos:
- [ ] Change namespacing from `Authorizer.X` to something else.

**Comment by fteem** [comment]
@mosic I am having some trouble testing this out, even after fixing some stuff that I've broken. I am getting this when -media is trying to fetch a snapshot: 
```
[info] Sent 500 in 2775ms
[error] #PID<0.541.0> running EvercamMedia.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /v1/cameras/phony_camera/live/snapshot.jpg?api_id=04e2d33a&api_key=2b62908e4a665daa66a512da024154ff
** (exit) :badarg
```

**Comment by mosic** [comment]
@fteem Sure, ping me today. Have you tried rebasing onto the latest master? I recently made a change to the `CamClient` that may affect that.

**Comment by fteem** [comment]
@mosic I managed to get this working.

**Comment by mosic** [comment]
@fteem I just tested this and realized we forgot something: the live/snapshot endpoint still needs to work with the requests redirected from evercam-api, because the Android app etc. will keep using them. Can you add a check for "token" parameter and use the old way if it's present?

**Comment by mosic** [comment]
Minor thing - `AccessRightConstantsTest` can be removed now because the constants were removed.

**Comment by fteem** [comment]
@mosic I made the endpoint backwards compatible, can you review this please? Thanks!

**Comment by mosic** [comment]
@fteem Just tried it locally. I ran it with valid credentials but replaced the api key with "xxx" in the following examples.

Making a request to http://localhost:9292/v1/cameras/austin/live/snapshot?api_id=ae22f256&api_key=xxx returns a 401 response:

```
{
  "error": {
    "message": "Invalid API keys"
  }
}
```
This works normally with the master branch, a snapshot is returned.

Making a request to http://localhost:4000/v1/cameras/austin/live/snapshot?api_id=ae22f256&api_key=xxx returns a 500 error:

```
iex(1)> [info] GET /v1/cameras/austin/live/snapshot
[debug] SELECT u0."id", u0."country_id", u0."username", u0."password", u0."firstname", u0."lastname", u0."email", u0."api_id", u0."api_key", u0."billing_id", u0."token_expires_at", u0."confirmed_at", u0."updated_at", u0."created_at" FROM "users" AS u0 WHERE (u0."api_id" = $1) AND (u0."api_key" = $2) ["ae22f256", "xxx"] OK query=2.1ms
[debug] SELECT a0."id", a0."user_id", a0."client_id", a0."grantor_id", a0."is_revoked", a0."expires_at", a0."request", a0."refresh", a0."updated_at", a0."created_at" FROM "access_tokens" AS a0 WHERE (((a0."user_id" = $1) AND (a0."is_revoked" = FALSE)) AND (a0."expires_at" > $2)) [49, {{2015, 12, 2}, {11, 44, 12, 0}}] OK query=0.3ms
[debug] Processing by EvercamMedia.SnapshotController.show/2
  Parameters: %{"api_id" => "ae22f256", "api_key" => "xxx", "id" => "austin"}
  Pipelines: [:api, :auth]
[info] Sent 500 in 9ms
[error] #PID<0.592.0> running EvercamMedia.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /v1/cameras/austin/live/snapshot?api_id=ae22f256&api_key=xxx
** (exit) an exception was raised:
    ** (Ecto.QueryError) deps/ecto/lib/ecto/association.ex:631: field `Camera.snapshot_id` in `join` does not exist in the model source in query:

from s in Snapshot,
  join: c in Camera,
  on: c.snapshot_id == s.camera_id,
  where: c.exid == ^"austin",
  limit: 1

        (elixir) lib/macro.ex:194: anonymous fn/3 in Macro.do_prewalk/3
        (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:193: Macro.do_prewalk/3
        (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
        (evercam_media) lib/evercam_media/permissions/snapshot.ex:31: EvercamMedia.Permissions.Snapshot.can_access?/3
        (evercam_media) web/controllers/snapshot_controller.ex:19: EvercamMedia.SnapshotController.show/2
        (evercam_media) web/controllers/snapshot_controller.ex:1: EvercamMedia.SnapshotController.action/2
        (evercam_media) web/controllers/snapshot_controller.ex:1: EvercamMedia.SnapshotController.phoenix_controller_pipeline/2
        (evercam_media) lib/phoenix/router.ex:255: EvercamMedia.Router.dispatch/2
        (evercam_media) web/router.ex:1: EvercamMedia.Router.do_call/2
```

**Pull request closed without merging**
