### PR TITLE
Improve camera workers

### PR DESCRIPTION
**Pull request by shankardevy**

### CODE REVIEW

**Comment by mosic** [comment]
@shankardevy Is this ready to merge or do you plan on doing more testing?

**Comment by shankardevy** [comment]
With this merge, it's likely that we see more errors in the log because I have removed the try/rescue. I removed those try/rescue because I think wrapping different things http calls, pg query and cache updates all in a single try statement is bit unclean and hides the obvious errors which we need to deal with in first place.  Most importantly when http requests are in the `try` and a subsequent db query or any other command fails, we don't pull the uploaded snapshot from the s3. 

For these reasons I have removed the `try/rescue` and let the process fail with ugly messages. It should be possible to pattern match the error and keep the code clean and lean in the next few commits following this work.

**Comment by mosic** [comment]
That's fine, but you haven't answered my question though. There are some issues with the code, but I'll handle them after I merge the frequency branch.

**Comment by shankardevy** [comment]
@mosic looking at the time, it looks like we both commented on the same time. Commenting and merging this branch was the last thing that I did before checking out of office. I have just seen your comment.

**Pull request merged**
