### PR TITLE
Intialized Documentation by adding ex_docs and also created docs with…

### PR DESCRIPTION
**Pull request by ijunaidfarooq**
… mix docs

### CODE REVIEW

**Comment by ijunaidfarooq** [comment]
By now.. 

this is just a branch for me and sir @azharmalik3 to work on..

I only made changes to `mix.exs` for adding `deps` and few changes here

```
  def project do
    [app: :evercam_media,
     name: "EvercamMedia",
     version: "1.0.1",
     elixir: "~> 1.3.0",
     elixirc_paths: elixirc_paths(Mix.env),
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     compilers: [:phoenix] ++ Mix.compilers,
     source_url: "https://github.com/evercam/evercam-media",
     aliases: aliases,
     docs: [extras: ["README.md"]],
     deps: deps]
  end
```

**Comment by mosic** [comment]
@ijunaidfarooq I'm against this change. There is no reason to add ~20k lines of auto-generated documentation to the repo. I just added `doc` directory to the `.gitignore` to prevent this from happening by accident: https://github.com/evercam/evercam-media/commit/a107ac8e795c0b4139bd0d76e99c4530c1534043 

I see two scenarios for reading documentation:
* offline (in development) - just run `mix docs`. Everything works great, even the search.
* online - you'd need to publish `evercam-media` as a hex package, so the documentation would be published to hexdocs. I don't think that's a good idea, but it's an option.

This PR doesn't replace (or replace) either of those two options.

**Comment by mosic** [comment]
@ijunaidfarooq I am, however, for adding `ex_doc`, so the documentation can be generated with `mix docs`. If you create a PR for it I'll merge it.

**Comment by ijunaidfarooq** [comment]
@mosic thanks for your comments on this. What you think about making such documentation online?

Isn't it good to elaborate what are we doing in Modules? that in case if a third person comes across and wants to join in?

I wonder why all others having their docs online. Because not every other person first clone the repo to see the docs locally :)

**Comment by ijunaidfarooq** [comment]
@mosic moreover why you think that's not a good idea? 

>  so the documentation would be published to hexdocs. I don't think that's a good idea, but it's an option.

**Comment by marcoherbst** [comment]
@ijunaidfarooq , his point is that the generated docs should not be included in the repo. That sounds correct to me. Have a look what others are doing.

**Comment by mosic** [comment]
@ijunaidfarooq All other projects that you are seeing are packages (i.e. plugins), not applications. It seems like a mismatch to publish evercam-media on hex.pm.

**Pull request closed without merging**
