### PR TITLE
added motiondetection

### PR DESCRIPTION
**Pull request by eugenehp**
added basic motion detection functionality

### CODE REVIEW

**Comment by eugenehp** [comment]
@mosic @marcoherbst this one is ready to be merged too.

**Comment by mosic** [comment]
@eugenehp Thanks, I'll test this out later/tomorrow.

**Comment by eugenehp** [comment]
@mosic sounds great. thanks Miloš. Have a great weekend! :smile

**Comment by mosic** [comment]
@eugenehp Hey Eugene, I needed to add some changes to your pull request and just now realized I can't do that since it's not under `evercam-media` repo, so I created a mirror of this and updated it there: https://github.com/evercam/evercam-media/pull/33

Is that a problem for you?

**Comment by mosic** [comment]
Discussion continued at https://github.com/evercam/evercam-media/pull/33

**Pull request closed without merging**
