### PR TITLE
Use ExVCR tool to mock OnVIF tests

### PR DESCRIPTION
**Pull request by jgarciasacristan**
Change the OnVIF unit tests to mock the OnVIF Web Service responses using https://github.com/parroty/exvcr tool. That only leaves 9 tests that use the external camera. I cannot mock these tests as they really verify that presets have been changed and that the camera has been moved. They are now isolated in controllers/onvifptz_controller_external_test.exs and onvif/external_ptz_tests.exs and can be easily excluded.

### CODE REVIEW

**Comment by jgarciasacristan** [comment]
As promised a long time ago. :)

**Comment by marcoherbst** [comment]
:)

On 16 April 2016 at 20:24, Jose C Garcia-Sacristan <notifications@github.com
> wrote:

> As promised a long time ago. :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/pull/196#issuecomment-210877034>
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@jgarciasacristan This seems to work nicely, but I'm getting a strange output when running tests even though all of them seem to pass. Do you see the same?

```
mix.exs:96: warning: redefining module Mix.Tasks.Compile.Make
mix.exs:107: warning: redefining module Mix.Tasks.Clean.Make
rm -f -r priv_dir/*
cc -g -O3 -ansi -pedantic -Wall -Wextra -Wno-declaration-after-statement -Wno-missing-field-initializers -Wno-pedantic -Wno-implicit-function-declaration -I/home/jack/kerl/18_1/erts-7.1/include -fPIC -shared  -o priv_dir/lib_elixir_motiondetection.so src/lib_elixir_motiondetection.c -ljpeg

Excluding tags: [skip: true]

........................................................2016-04-18 14:13:46.165 request_id=mkmgnijvemr55jbukcc47gnq6312cvb5 [error] Error invoking GetUnknownAction. URL: http://recorded_response/onvif/DeviceIO auth: admin:mehcam. Request: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\"\n    xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\n    xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis=200401-wss-wssecurity-utility-1.0.xsd\">\n    <SOAP-ENV:Header><wsse:Security><wsse:UsernameToken>\n    <wsse:Username>admin</wsse:Username>\n    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">ximk+2yZHsG5b8SlFErX/CpKqpM=</wsse:Password>\n    <wsse:Nonce>wp06w708N8OQKsOcwoh1wo1sw6jDlMObG3V+w7Q7Xg==</wsse:Nonce>\n    <wsu:Created>2016-04-18T14:13:46Z</wsu:Created></wsse:UsernameToken>\n    </wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body>\n    <tmd:GetUnknownAction xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\"></tmd:GetUnknownAction>\n    </SOAP-ENV:Body></SOAP-ENV:Envelope>". Response %HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value>\r\n<env:Subcode><env:Value>ter:ActionNotSupported</env:Value>\r\n<env:Subcode><env:Value>ter:InvalidOperation</env:Value>\r\n</env:Subcode>\r\n</env:Subcode>\r\n</env:Code>\r\n<env:Reason><env:Text xml:lang=\"en\">Optional Action Not Implemented</env:Text>\r\n</env:Reason>\r\n</env:Fault>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "2247", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Thu, 25 Feb 2016 11:33:09 GMT", Server: "App-webs/"], status_code: 500}.
.2016-04-18 14:13:46.258 request_id=durntr5ud7mt7qcrh8r4dhuplm0spq90 [error] Error invoking GetNetworkInterfaces. URL: http://recorded_response/onvif/device_service auth: admin:foo. Request: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\"\n    xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\n    xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis=200401-wss-wssecurity-utility-1.0.xsd\">\n    <SOAP-ENV:Header><wsse:Security><wsse:UsernameToken>\n    <wsse:Username>admin</wsse:Username>\n    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">fqT6Rg7JpQb58IdVhvVykYG4Q2c=</wsse:Password>\n    <wsse:Nonce>wpwwwqsgKkfCogPCpjkiw4bCpsODwrZlRcKJcsKIEQ==</wsse:Nonce>\n    <wsu:Created>2016-04-18T14:13:46Z</wsu:Created></wsse:UsernameToken>\n    </wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body>\n    <tds:GetNetworkInterfaces xmlns:tds=\"http://www.onvif.org/ver20/device/wsdl\"></tds:GetNetworkInterfaces>\n    </SOAP-ENV:Body></SOAP-ENV:Envelope>". Response %HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><env:Fault><env:Code><env:Value>env:Sender</env:Value>\r\n<env:Subcode><env:Value>ter:NotAuthorized</env:Value>\r\n</env:Subcode>\r\n</env:Code>\r\n<env:Reason><env:Text xml:lang=\"en\">The action requested requires authorization and the sender is not authorized</env:Text>\r\n</env:Reason>\r\n</env:Fault>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "2211", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Thu, 25 Feb 2016 11:33:08 GMT", Server: "App-webs/"], status_code: 400}.
.2016-04-18 14:13:46.346 request_id=im3ejqv3oj5413ojrtr24bk35f5ptuci [error] Error invoking GetSnapshotUri. URL: http://recorded_response/onvif/Media auth: admin:mehcam. Request: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\"\n    xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\n    xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis=200401-wss-wssecurity-utility-1.0.xsd\">\n    <SOAP-ENV:Header><wsse:Security><wsse:UsernameToken>\n    <wsse:Username>admin</wsse:Username>\n    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">9qqRKlaQT7kIinsDEObZdFhPvyA=</wsse:Password>\n    <wsse:Nonce>dWPCosOVw5BWw71VwrNjZx7CvX8Iw4QqGcOLbhY=</wsse:Nonce>\n    <wsu:Created>2016-04-18T14:13:46Z</wsu:Created></wsse:UsernameToken>\n    </wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body>\n    <trt:GetSnapshotUri xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\"><ProfileToken>Foo</ProfileToken></trt:GetSnapshotUri>\n    </SOAP-ENV:Body></SOAP-ENV:Envelope>". Response %HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><env:Fault><env:Code><env:Value>env:Sender</env:Value>\r\n<env:Subcode><env:Value>ter:InvalidArgVal</env:Value>\r\n<env:Subcode><env:Value>ter:NoProfile</env:Value>\r\n</env:Subcode>\r\n</env:Subcode>\r\n</env:Code>\r\n<env:Reason><env:Text xml:lang=\"en\">The requested profile token ProfileToken does not exist.</env:Text>\r\n</env:Reason>\r\n<env:Node>http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver</env:Node>\r\n<env:Role>http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver</env:Role>\r\n<env:Detail><env:Text>No such profile</env:Text>\r\n</env:Detail>\r\n</env:Fault>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "2491", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Thu, 25 Feb 2016 11:32:58 GMT", Server: "App-webs/"], status_code: 500}.
.2016-04-18 14:13:46.438 request_id=2k9ra6prektbjsupn1mngeh9n4jeems0 [error] Error invoking GetServiceCapabilities. URL: http://recorded_response/onvif/Display auth: admin:mehcam. Request: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://www.w3.org/2003/05/soap-envelope\"\n    xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"\n    xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis=200401-wss-wssecurity-utility-1.0.xsd\">\n    <SOAP-ENV:Header><wsse:Security><wsse:UsernameToken>\n    <wsse:Username>admin</wsse:Username>\n    <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">V1/hlS+OngHpjoG1ODhWh3jnRZg=</wsse:Password>\n    <wsse:Nonce>YsOJIcOdacKALW1wwqnDi8OJwqzDksK8fQTDg8Ocw7te</wsse:Nonce>\n    <wsu:Created>2016-04-18T14:13:46Z</wsu:Created></wsse:UsernameToken>\n    </wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body>\n    <tls:GetServiceCapabilities xmlns:tls=\"http://www.onvif.org/ver10/display/wsdl\"></tls:GetServiceCapabilities>\n    </SOAP-ENV:Body></SOAP-ENV:Envelope>". Response %HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value>\r\n<env:Subcode><env:Value>ter:ActionNotSupported</env:Value>\r\n<env:Subcode><env:Value>ter:InvalidOperation</env:Value>\r\n</env:Subcode>\r\n</env:Subcode>\r\n</env:Code>\r\n<env:Reason><env:Text xml:lang=\"en\">Optional Action Not Implemented</env:Text>\r\n</env:Reason>\r\n</env:Fault>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "2247", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Thu, 25 Feb 2016 11:33:15 GMT", Server: "App-webs/"], status_code: 500}.
......

Finished in 18.4 seconds (0.3s on load, 18.0s on tests)
66 tests, 0 failures, 1 skipped

Randomized with seed 571755
```

**Comment by jgarciasacristan** [comment]
These are outputs from the tests that are testing that the error message is
the expected.

**Comment by mosic** [comment]
@jgarciasacristan Ok, then I suggest that we capture the output and display it only if the test is failed, maybe using http://elixir-lang.org/docs/stable/ex_unit/ExUnit.CaptureLog.html

**Comment by jgarciasacristan** [comment]
I'll give it a try to the @tag :capture_log tonight. I tried to get it
working before and it did not work. I'll give it another try.

**Comment by mosic** [comment]
@jgarciasacristan Great, thank you.

**Comment by jgarciasacristan** [comment]
@tag :capture_log added

**Comment by mosic** [comment]
@jgarciasacristan Thanks again, merged into master.

**Pull request merged**
