### PR TITLE
Handle PTZ requests to cameras which don't support it (#233)

### PR DESCRIPTION
**Pull request by jgarciasacristan**
Better error handling of PTZ requests.

### CODE REVIEW

**Comment by mosic** [comment]
Thanks Jose, looks good. There were just a couple of small unnecessary whitespace additions, I cleaned them while rebasing. You can see the diff here: https://github.com/evercam/evercam-media/compare/c35bcb2d1018c2245129719061eba65caf006d36...e3424414bda47b7110fb512e1e374f2cfca00316 

What editor do you use? I added a `.editorconfig` config which you can use to ensure that the spacing is consistent with existing code: https://github.com/evercam/evercam-media/blob/master/.editorconfig 

More about this: http://editorconfig.org/

Also, it would be great if you could use rebase instead of merge when you need to get changes from master on your branch.

Thanks again :+1:

**Comment by marcoherbst** [comment]
Thanks @jgarciasacristan :+1:

**Comment by jgarciasacristan** [comment]
Hi Mosic,
I use sublime text. I thought I had it properly configured, but still some
issues. :-(
I'll try to configure the .editorconfig values into the sublime config when
I have time.
Thanks for the rebase suggestion, I will do that from now on. :-)
Jose

**Comment by mosic** [comment]
@jgarciasacristan Great, let me know if you have any issues with it. The main things are: spaces only, two spaces for indentation, no trailing whitespace, final newline always present. (and no multiple blank lines next to each other)

Not a big deal but it would make accepting PR's much quicker if I don't need to touch them afterwards :)

**Pull request closed without merging**
