### PR TITLE
ONVIF PTZ Routes

### PR DESCRIPTION
**Pull request by jgarciasacristan**
Hi Milos
Very first cut. Error handling is non existent. The goal is to have something for Liuting to start working in the UI. Tests are coded against a camera called mobile-mast-test that is really the mobile-mast camera available at http://149.13.244.32:8100. I have manually added it myself to my environment. Feel free of not merging the tests as they won't work in anyone else environment! One fix for this would be to add this camera to the default DB shipped with the environment. 
I forgot to add the delete route, but better not to mess with the code until reviewed and merged. I takes only 5 mins to add it as the method is available in the lib/onvif_ptz.ex file.
Cheers,
Jose

### CODE REVIEW

**Comment by mosic** [comment]
Hi Jose, nice work.

I've gone through the code and made a minor refactoring to improve readability/formatting and merged to master.

Tests calling a live camera isn't ideal but at this stage it's better than stubs (and certainly better than nothing). I'd suggest modified test runner to use a separate database (`evercam_tst`, which we also use for `evercam-api`) and to purge it before running tests, add the example camera, then let the tests run. Can you create a pull request for that?

Btw your code is now in production :)

**Comment by marcoherbst** [comment]
Excellent. Well done Jose.
M

On 25 August 2015 at 01:43, Miloš Mošić <notifications@github.com> wrote:

> Hi Jose, nice work.
>
> I've gone through the code and made a minor refactoring to improve
> readability/formatting and merged to master.
>
> Tests calling a live camera isn't ideal but at this stage it's better than
> stubs (and certainly better than nothing). I'd suggest modified test runner
> to use a separate database (evercam_tst, which we also use for evercam-api)
> and to purge it before running tests, add the example camera, then let the
> tests run. Can you create a pull request for that?
>
> Btw your code is now in production :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/pull/34#issuecomment-134427185>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
Thanks!
@mosic  Thank you for all the refactoring. I'll take a look at what you have done to improve my elixir code formatting. :-)
I am aware at the tests issues. I'll change the code to use evercam_tst. Can you point me to an example  where this table is  updated/ an example where a camera info is inserted to a table?

**Comment by mosic** [comment]
Sure, you can take a look at how `evercam-dashboard` does it:

https://github.com/evercam/evercam-dashboard/blob/master/spec/spec_helper.rb
https://github.com/evercam/evercam-dashboard/blob/master/spec/factories/camera.rb

**Comment by jgarciasacristan** [comment]
Thank you Milos.  I'll add more tests for the routes and populate the
evercam_tst with the test info. But first I want to really understand how
evercam_media app works and learn more about Phoenix. I am supposed to talk
at least 40 mins about Elixir, Phoenix and my experience as Evercam
collaborator in 17 days and 12 hours! (See countdown at
http://functionalkats.com/ )

**Comment by mosic** [comment]
I suggest asking Marco to take half of the talk, it worked for me ;)

Good luck with the talk!

**Comment by jgarciasacristan** [comment]
@marcoherbst  What do you think? Originally the idea was to give an introduction to Phoenix and then talk about my experience with Evercam. But it will be great if you can join me and change the presentation to talk more about Evercam and the opportunity to future "Alchemists" to contribute to a real world Elixir app.

**Pull request merged**
