### PR TITLE
Added cc emails in camera share and create

### PR DESCRIPTION
**Pull request by azharmalik3**
@mosic

### CODE REVIEW

**Comment by marcoherbst** [comment]
Nice, but for create camera please use bcc

also bcc marco and vinnie for shares.

m

**Comment by marcoherbst** [comment]
This is temporary while we get this working.

**Comment by mosic** [comment]
Closing in favor of https://github.com/evercam/evercam-media/commit/16aa614ea863867a8e76c90d5206f235858874f4 and https://github.com/evercam/mailgun/commit/e1f009d70adbefdfe04cdcbbf0456b2867ce4ea9.

I think that this feature will be confusing to users though.

**Comment by marcoherbst** [comment]
Thanks Milos.

You're right. It's a temporary step, until we come up with something better. @vinnieq 

M

**Pull request closed without merging**
